FROM ubuntu:20.04
LABEL maintainer="firstfile"
RUN apt update && \
    apt install nginx -y && \
    echo "Hello Pooja" > /var/www/html/index.nginx-debian.html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
